import unittest
import logging
import os

import pandas
from decimal import Decimal

from exchanges.kraken import parse_orders, parse_flows


class TestKrakenAPI(unittest.TestCase):
    """
    Testing P&L calculation from Bittrex.
    """

    def setUp(self):
        self._deposits = pandas.read_pickle(os.path.abspath(os.sep.join(['tests-data', 'kraken-deposits.pkl'])))
        self._withdrawals = pandas.read_pickle(os.path.abspath(os.sep.join(['tests-data', 'kraken-withdrawals.pkl'])))
        logging.info('loading example withdrawals file: {}'.format(self._withdrawals))
        logging.info('loading example deposits file: {}'.format(self._deposits))

    def test_parsing_flows(self):
        deposits = {'L4WZSK-XKUFF-ULRXRT': {'refid': 'QCCILXH-7D774O-Z6YXO6', 'time': Decimal('1500621623.3172'),
                                            'type': 'deposit', 'aclass': 'currency', 'asset': 'ZEUR',
                                            'amount': '500.0000', 'fee': '0.0000', 'balance': '507.3638'},
                    'LN22GR-D7JEM-WREQHG': {'refid': 'Q4G46G5-J4EVIZ-XCEZZJ', 'time': Decimal('1499930741.5098'),
                                            'type': 'deposit', 'aclass': 'currency', 'asset': 'EOS',
                                            'amount': '255.7618000000', 'fee': '2.0000000000',
                                            'balance': '253.7618000000'},
                    'LJNJSI-JASTK-4UCSVT': {'refid': 'QCCHOFH-SNP7O4-ZC7TF4', 'time': Decimal('1499758934.1354'),
                                            'type': 'deposit', 'aclass': 'currency', 'asset': 'ZEUR',
                                            'amount': '500.0000', 'fee': '0.0000', 'balance': '500.0000'}}
        withdrawals = {'L72ZCB-ZJBKY-7ZXENF': {'refid': 'A2B3JVQ-4QMY6G-VF4HWM', 'time': Decimal('1499845194.9223'),
                                               'type': 'withdrawal', 'aclass': 'currency', 'asset': 'XETH',
                                               'amount': '-2.2413500000', 'fee': '0.0050000000',
                                               'balance': '0.0000065900'}}
        flows = parse_flows(withdrawals, deposits)
        self.assertSequenceEqual(flows.columns.tolist(), ('date', 'amount', 'asset', 'fee', 'exchange'))
        self.assertAlmostEqual(float(flows[flows['asset'] == 'EOS']['amount'].sum()), 255.7618, places=6)

    def test_parsing_orders(self):
        kraken_data = {'ORRIGN-NSRTN-PKG6VE': {'refid': None, 'userref': None, 'status': 'closed', 'reason': None,
                                               'opentm': Decimal('1500358395.7263'),
                                               'closetm': Decimal('1500358412.1722'), 'starttm': 0, 'expiretm': 0,
                                               'descr': {'pair': 'XBTEUR', 'type': 'buy', 'ordertype': 'limit',
                                                         'price': '1950.000', 'price2': '0', 'leverage': 'none',
                                                         'order': 'buy 0.01025641 XBTEUR @ limit 1950.000'},
                                               'vol': '0.01025641', 'vol_exec': '0.01025641', 'cost': '19.932',
                                               'fee': '0.031', 'price': '1943.427', 'misc': '', 'oflags': 'fciq',
                                               'trades': ['TD2SRE-EOASM-NDOV73']},
                       'ODOJEM-EXORO-E5GWTN': {'refid': None, 'userref': None, 'status': 'canceled',
                                               'reason': 'User canceled', 'opentm': Decimal('1500358311.3743'),
                                               'closetm': Decimal('1500358355.6171'), 'starttm': 0, 'expiretm': 0,
                                               'descr': {'pair': 'XBTEUR', 'type': 'sell', 'ordertype': 'limit',
                                                         'price': '1960.000', 'price2': '0', 'leverage': 'none',
                                                         'order': 'sell 0.01020408 XBTEUR @ limit 1960.000'},
                                               'vol': '0.01020408', 'vol_exec': '0.00000000', 'cost': '0.00000',
                                               'fee': '0.00000', 'price': '0.00000', 'misc': '', 'oflags': 'fciq'},
                       'OWFI52-YZ57H-6DQ5VJ': {'refid': None, 'userref': None, 'status': 'closed', 'reason': None,
                                               'opentm': Decimal('1500320279.6568'),
                                               'closetm': Decimal('1500320538.6233'), 'starttm': 0, 'expiretm': 0,
                                               'descr': {'pair': 'LTCEUR', 'type': 'buy', 'ordertype': 'limit',
                                                         'price': '36.70000', 'price2': '0', 'leverage': 'none',
                                                         'order': 'buy 5.00000000 LTCEUR @ limit 36.70000'},
                                               'vol': '5.00000000', 'vol_exec': '5.00000000', 'cost': '183.46373',
                                               'fee': '0.29354', 'price': '36.69275', 'misc': '', 'oflags': 'fciq',
                                               'trades': ['TXBH2R-MID32-UYFQHH', 'TSOBY5-R6NCW-MNI4KT',
                                                          'T4Q7WN-3YYAJ-ARFUQG', 'TLNY22-3SUN5-JI7MTV',
                                                          'TXDFWF-WBGBS-7J7DYX']},
                       'OLLSKP-POGIQ-XHGRCY': {'refid': None, 'userref': None, 'status': 'canceled',
                                               'reason': 'User canceled', 'opentm': Decimal('1500215180.7903'),
                                               'closetm': Decimal('1500320265.1826'), 'starttm': 0, 'expiretm': 0,
                                               'descr': {'pair': 'ETHEUR', 'type': 'buy', 'ordertype': 'limit',
                                                         'price': '115.00000', 'price2': '0', 'leverage': 'none',
                                                         'order': 'buy 1.00000000 ETHEUR @ limit 115.00000'},
                                               'vol': '1.00000000', 'vol_exec': '0.00000000', 'cost': '0.00000',
                                               'fee': '0.00000', 'price': '0.00000', 'misc': '', 'oflags': 'fciq'},
                       'OUE5BK-DZMBK-FXQMKA': {'refid': None, 'userref': None, 'status': 'closed', 'reason': None,
                                               'opentm': Decimal('1500213640.125'),
                                               'closetm': Decimal('1500213751.292'), 'starttm': 0, 'expiretm': 0,
                                               'descr': {'pair': 'ETHEUR', 'type': 'buy', 'ordertype': 'limit',
                                                         'price': '137.00000', 'price2': '0', 'leverage': 'none',
                                                         'order': 'buy 1.00000000 ETHEUR @ limit 137.00000'},
                                               'vol': '1.00000000', 'vol_exec': '1.00000000', 'cost': '136.80013',
                                               'fee': '0.21888', 'price': '136.80013', 'misc': '', 'oflags': 'fciq',
                                               'trades': ['TWTEFQ-3NGJG-37ZTW3']},
                       'OZZCA7-DNHIX-HBWZPD': {'refid': None, 'userref': None, 'status': 'canceled',
                                               'reason': 'User canceled', 'opentm': Decimal('1500213280.3717'),
                                               'closetm': Decimal('1500213625.6315'), 'starttm': 0, 'expiretm': 0,
                                               'descr': {'pair': 'ETHEUR', 'type': 'buy', 'ordertype': 'limit',
                                                         'price': '133.30000', 'price2': '0', 'leverage': 'none',
                                                         'order': 'buy 1.00000000 ETHEUR @ limit 133.30000'},
                                               'vol': '1.00000000', 'vol_exec': '0.00000000', 'cost': '0.00000',
                                               'fee': '0.00000', 'price': '0.00000', 'misc': '', 'oflags': 'fciq'},
                       'O5XWA6-P7PA7-P2DIW3': {'refid': None, 'userref': None, 'status': 'closed', 'reason': None,
                                               'opentm': Decimal('1500212395.972'),
                                               'closetm': Decimal('1500212763.063'), 'starttm': 0, 'expiretm': 0,
                                               'descr': {'pair': 'XRPEUR', 'type': 'buy', 'ordertype': 'limit',
                                                         'price': '0.126300', 'price2': '0', 'leverage': 'none',
                                                         'order': 'buy 395.88281868 XRPEUR @ limit 0.126300'},
                                               'vol': '395.88281868', 'vol_exec': '395.88281868', 'cost': '50.000000',
                                               'fee': '0.080000', 'price': '0.126300', 'misc': '', 'oflags': 'fciq',
                                               'trades': ['TQUMO4-AG42S-2E3DMY']},
                       'OOYLK6-NOSJF-JLN3KH': {'refid': None, 'userref': None, 'status': 'canceled',
                                               'reason': 'User canceled', 'opentm': Decimal('1500212307.7967'),
                                               'closetm': Decimal('1500212354.9371'), 'starttm': 0, 'expiretm': 0,
                                               'descr': {'pair': 'XRPEUR', 'type': 'buy', 'ordertype': 'limit',
                                                         'price': '0.126010', 'price2': '0', 'leverage': 'none',
                                                         'order': 'buy 396.79390524 XRPEUR @ limit 0.126010'},
                                               'vol': '396.79390524', 'vol_exec': '0.00000000', 'cost': '0.00000000',
                                               'fee': '0.00000000', 'price': '0.00000000', 'misc': '',
                                               'oflags': 'fciq'},
                       'OBRMOO-KEPIU-YWTN4R': {'refid': None, 'userref': None, 'status': 'closed', 'reason': None,
                                               'opentm': Decimal('1500211865.4638'),
                                               'closetm': Decimal('1500211868.0617'), 'starttm': 0, 'expiretm': 0,
                                               'descr': {'pair': 'XRPEUR', 'type': 'buy', 'ordertype': 'limit',
                                                         'price': '0.128000', 'price2': '0', 'leverage': 'none',
                                                         'order': 'buy 390.62500000 XRPEUR @ limit 0.128000'},
                                               'vol': '390.62500000', 'vol_exec': '390.62500000', 'cost': '48.867187',
                                               'fee': '0.127054', 'price': '0.125100', 'misc': '', 'oflags': 'fciq',
                                               'trades': ['TZRI7X-UVZ4V-QKSFPO']},
                       'OKAZSI-KTFYG-PNJRPC': {'refid': None, 'userref': None, 'status': 'closed', 'reason': None,
                                               'opentm': Decimal('1500036544.5181'),
                                               'closetm': Decimal('1500036546.1024'), 'starttm': 0, 'expiretm': 0,
                                               'descr': {'pair': 'LTCEUR', 'type': 'sell', 'ordertype': 'market',
                                                         'price': '0', 'price2': '0', 'leverage': 'none',
                                                         'order': 'sell 1.99739000 LTCEUR @ market'},
                                               'vol': '1.99739000', 'vol_exec': '1.99739000', 'cost': '75.97806',
                                               'fee': '0.19754', 'price': '38.03867', 'misc': '', 'oflags': 'fciq',
                                               'trades': ['TKOMOP-6LPCZ-FPJQEO', 'TUMEYD-Q7ESV-DOXB67']},
                       'O7DE77-BC35I-W3ABKY': {'refid': None, 'userref': None, 'status': 'canceled',
                                               'reason': 'User canceled', 'opentm': Decimal('1500036426.5256'),
                                               'closetm': Decimal('1500036451.5372'), 'starttm': 0, 'expiretm': 0,
                                               'descr': {'pair': 'LTCEUR', 'type': 'sell', 'ordertype': 'limit',
                                                         'price': '38.46500', 'price2': '0', 'leverage': 'none',
                                                         'order': 'sell 1.99739000 LTCEUR @ limit 38.46500'},
                                               'vol': '1.99739000', 'vol_exec': '0.00000000', 'cost': '0.00000',
                                               'fee': '0.00000', 'price': '0.00000', 'misc': '', 'oflags': 'fciq'},
                       'OX3HS2-FWF56-WBWTEV': {'refid': None, 'userref': None, 'status': 'closed', 'reason': None,
                                               'opentm': Decimal('1500036370.2567'),
                                               'closetm': Decimal('1500036446.3614'), 'starttm': 0, 'expiretm': 0,
                                               'descr': {'pair': 'ETHEUR', 'type': 'sell', 'ordertype': 'limit',
                                                         'price': '170.50001', 'price2': '0', 'leverage': 'none',
                                                         'order': 'sell 2.18178000 ETHEUR @ limit 170.50001'},
                                               'vol': '2.18178000', 'vol_exec': '2.18178000', 'cost': '371.99351',
                                               'fee': '0.59519', 'price': '170.50001', 'misc': '', 'oflags': 'fciq',
                                               'trades': ['T3N7SN-KV66R-7YRVRK']},
                       'OSWBSJ-KQI6S-DXTTQM': {'refid': None, 'userref': None, 'status': 'closed', 'reason': None,
                                               'opentm': Decimal('1499931235.3944'),
                                               'closetm': Decimal('1499931239.9111'), 'starttm': 0, 'expiretm': 0,
                                               'descr': {'pair': 'EOSETH', 'type': 'sell', 'ordertype': 'market',
                                                         'price': '0', 'price2': '0', 'leverage': 'none',
                                                         'order': 'sell 253.76180000 EOSETH @ market'},
                                               'vol': '253.76180000', 'vol_exec': '253.76180000', 'cost': '2.117642',
                                               'fee': '0.005505', 'price': '0.008345', 'misc': '', 'oflags': 'fciq',
                                               'trades': ['TCCGJY-N2HO3-PZ764O']},
                       'OUR7EF-ZGYDG-IWK7M6': {'refid': None, 'userref': None, 'status': 'canceled',
                                               'reason': 'User canceled', 'opentm': Decimal('1499931123.998'),
                                               'closetm': Decimal('1499931191.3428'), 'starttm': 0, 'expiretm': 0,
                                               'descr': {'pair': 'EOSETH', 'type': 'sell', 'ordertype': 'limit',
                                                         'price': '0.008600', 'price2': '0', 'leverage': 'none',
                                                         'order': 'sell 253.76180000 EOSETH @ limit 0.008600'},
                                               'vol': '253.76180000', 'vol_exec': '0.00000000', 'cost': '0.00000000',
                                               'fee': '0.00000000', 'price': '0.00000000', 'misc': '',
                                               'oflags': 'fcib'},
                       'OBHUW4-TJ7YP-RLHQ4D': {'refid': None, 'userref': None, 'status': 'closed', 'reason': None,
                                               'opentm': Decimal('1499927067.5728'),
                                               'closetm': Decimal('1499927068.1846'), 'starttm': 0, 'expiretm': 0,
                                               'descr': {'pair': 'ETHXBT', 'type': 'buy', 'ordertype': 'market',
                                                         'price': '0', 'price2': '0', 'leverage': 'none',
                                                         'order': 'buy 0.05000000 ETHXBT @ market'},
                                               'vol': '0.05000000', 'vol_exec': '0.05000000', 'cost': '0.004486',
                                               'fee': '0.000012', 'price': '0.089720', 'misc': '', 'oflags': 'fciq',
                                               'trades': ['T2IBOD-KIPFH-XR54MB']},
                       'O46K5J-WU7YO-COB3FS': {'refid': None, 'userref': None, 'status': 'closed', 'reason': None,
                                               'opentm': Decimal('1499926947.7688'),
                                               'closetm': Decimal('1499926949.165'), 'starttm': 0, 'expiretm': 0,
                                               'descr': {'pair': 'LTCXBT', 'type': 'sell', 'ordertype': 'market',
                                                         'price': '0', 'price2': '0', 'leverage': 'none',
                                                         'order': 'sell 0.50000000 LTCXBT @ market'},
                                               'vol': '0.50000000', 'vol_exec': '0.50000000', 'cost': '0.009623',
                                               'fee': '0.000025', 'price': '0.019247', 'misc': '', 'oflags': 'fcib',
                                               'trades': ['TPWQDL-E6T3S-BIUOQO']},
                       'OSWKIU-PLZMI-VX3UYG': {'refid': None, 'userref': None, 'status': 'closed', 'reason': None,
                                               'opentm': Decimal('1499926762.8833'),
                                               'closetm': Decimal('1499926765.4977'), 'starttm': 0, 'expiretm': 0,
                                               'descr': {'pair': 'ETHXBT', 'type': 'buy', 'ordertype': 'market',
                                                         'price': '0', 'price2': '0', 'leverage': 'none',
                                                         'order': 'buy 0.01000000 ETHXBT @ market'},
                                               'vol': '0.01000000', 'vol_exec': '0.01000000', 'cost': '0.000900',
                                               'fee': '0.000002', 'price': '0.090000', 'misc': '', 'oflags': 'fciq',
                                               'trades': ['TKAXGT-TZ2YV-CFJUDA']},
                       'OUT46P-3FCZ4-IBIIM3': {'refid': None, 'userref': None, 'status': 'closed', 'reason': None,
                                               'opentm': Decimal('1499926557.1823'),
                                               'closetm': Decimal('1499926561.706'), 'starttm': 0, 'expiretm': 0,
                                               'descr': {'pair': 'ETHXBT', 'type': 'buy', 'ordertype': 'market',
                                                         'price': '0', 'price2': '0', 'leverage': 'none',
                                                         'order': 'buy 0.00964000 ETHXBT @ market'},
                                               'vol': '0.00964000', 'vol_exec': '0.00964000', 'cost': '0.000871',
                                               'fee': '0.000002', 'price': '0.090353', 'misc': '', 'oflags': 'fciq',
                                               'trades': ['TBWKBZ-2HLYF-35Y6LL']},
                       'OIXSHR-DYHSO-VGSA6N': {'refid': None, 'userref': None, 'status': 'closed', 'reason': None,
                                               'opentm': Decimal('1499926375.1952'),
                                               'closetm': Decimal('1499926377.6601'), 'starttm': 0, 'expiretm': 0,
                                               'descr': {'pair': 'LTCXBT', 'type': 'sell', 'ordertype': 'limit',
                                                         'price': '0.019298', 'price2': '0', 'leverage': 'none',
                                                         'order': 'sell 0.50000000 LTCXBT @ limit 0.019298'},
                                               'vol': '0.50000000', 'vol_exec': '0.50000000', 'cost': '0.009649',
                                               'fee': '0.000025', 'price': '0.019298', 'misc': '', 'oflags': 'fcib',
                                               'trades': ['TEY4TQ-KKWWB-IH6D5B']},
                       'OXOKNF-MPYDL-JZLM2I': {'refid': None, 'userref': None, 'status': 'closed', 'reason': None,
                                               'opentm': Decimal('1499838927.3371'),
                                               'closetm': Decimal('1499838930.3352'), 'starttm': 0, 'expiretm': 0,
                                               'descr': {'pair': 'ETHXBT', 'type': 'buy', 'ordertype': 'limit',
                                                         'price': '0.083850', 'price2': '0', 'leverage': 'none',
                                                         'order': 'buy 2.24985092 ETHXBT @ limit 0.083850'},
                                               'vol': '2.24985092', 'vol_exec': '2.24985092', 'cost': '0.188650',
                                               'fee': '0.000302', 'price': '0.083850', 'misc': '', 'oflags': 'fciq',
                                               'trades': ['TPAM55-GR362-IQJF7E']},
                       'OWLPQZ-F5RTF-R4DRVS': {'refid': None, 'userref': None, 'status': 'closed', 'reason': None,
                                               'opentm': Decimal('1499838746.4842'),
                                               'closetm': Decimal('1499838747.2381'), 'starttm': 0, 'expiretm': 0,
                                               'descr': {'pair': 'LTCXBT', 'type': 'buy', 'ordertype': 'limit',
                                                         'price': '0.019311', 'price2': '0', 'leverage': 'none',
                                                         'order': 'buy 3.00000000 LTCXBT @ limit 0.019311'},
                                               'vol': '3.00000000', 'vol_exec': '3.00000000', 'cost': '0.057900',
                                               'fee': '0.000150', 'price': '0.019300', 'misc': '', 'oflags': 'fciq',
                                               'trades': ['TFHXK4-6DYO7-RK5NMB']},
                       'O2ZJEH-L2YVT-JK6BHF': {'refid': None, 'userref': None, 'status': 'canceled',
                                               'reason': 'Out of funds', 'opentm': Decimal('1499838622.1544'),
                                               'closetm': Decimal('1499838634.9985'), 'starttm': 0, 'expiretm': 0,
                                               'descr': {'pair': 'XBTEUR', 'type': 'buy', 'ordertype': 'limit',
                                                         'price': '2023.440', 'price2': '0', 'leverage': 'none',
                                                         'order': 'buy 0.24710000 XBTEUR @ limit 2023.440'},
                                               'vol': '0.24710000', 'vol_exec': '0.24683968', 'cost': '499.465',
                                               'fee': '0.799', 'price': '2023.439', 'misc': 'partial', 'oflags': 'fciq',
                                               'trades': ['T3DLGY-FPVOE-EEYGEQ', 'TIZJAC-3O4WF-HHTCAU',
                                                          'TTC6V6-AGN6P-XVINYL', 'TYJDNY-HA434-ISPIEM']},
                       'OTFH4T-EH6E4-H6AOZQ': {'refid': None, 'userref': None, 'status': 'canceled',
                                               'reason': 'User canceled', 'opentm': Decimal('1499838302.9344'),
                                               'closetm': Decimal('1499838584.7761'), 'starttm': 0, 'expiretm': 0,
                                               'descr': {'pair': 'XBTEUR', 'type': 'buy', 'ordertype': 'limit',
                                                         'price': '2021.893', 'price2': '0', 'leverage': 'none',
                                                         'order': 'buy 0.24729000 XBTEUR @ limit 2021.893'},
                                               'vol': '0.24729000', 'vol_exec': '0.00000000', 'cost': '0.00000',
                                               'fee': '0.00000', 'price': '0.00000', 'misc': '', 'oflags': 'fciq'}}
        orders = parse_orders(kraken_data)
        eur_value = float(orders[['asset', 'qty']].groupby('asset').sum().loc['EUR']['qty'])
        self.assertSequenceEqual(orders.columns.tolist(), ('date', 'asset', 'qty', 'fee', 'exchange'))
        self.assertAlmostEqual(eur_value, 8.908523, places=6)

    def tearDown(self):
        pass


if __name__ == '__main__':
    logging.basicConfig(level=logging.INFO, format='%(asctime)s:%(name)s:%(levelname)s:%(message)s')
    unittest.main()
